import {useEffect,useState} from 'react'
import api from '../services/api'
import toast from 'react-hot-toast'
export default function AIAssistant(){
 const [risks,setRisks]=useState([]),[anomalies,setAnomalies]=useState([]),[question,setQuestion]=useState('Which employees have repeated late arrivals?'),[answer,setAnswer]=useState(null),[policyQuestion,setPolicyQuestion]=useState(''),[policyAnswer,setPolicyAnswer]=useState(null)
 useEffect(()=>{Promise.all([api.get('/ai/attendance-risk'),api.get('/ai/anomalies')]).then(([r,a])=>{setRisks(r.data);setAnomalies(a.data)})},[])
 const ask=async e=>{e.preventDefault();try{setAnswer((await api.post('/ai/hr-assistant',{question})).data)}catch(x){toast.error(x.response?.data?.detail||'Question not supported')}}
 const upload=async e=>{const body=new FormData();body.append('file',e.target.files[0]);try{await api.post('/policies',body,{headers:{'Content-Type':'multipart/form-data'}});toast.success('Policy indexed')}catch(x){toast.error(x.response?.data?.detail||'Upload failed')}}
 const askPolicy=async e=>{e.preventDefault();setPolicyAnswer((await api.post('/policies/ask',{question:policyQuestion})).data)}
 return <div className="page-container"><div className="card"><h3>Attendance Risk - Decision Support</h3><p className="text-muted">Transparent rules; never an automated disciplinary decision.</p>{risks.map(r=><div key={r.employee_id} className="alert"><b>{r.employee_name}: {r.risk_level} ({r.score})</b><div>{r.factors.join('; ')}</div></div>)}</div><div className="card"><h3>Anomaly Alerts</h3>{!anomalies.length?<p>No anomalies detected.</p>:anomalies.map((a,i)=><p key={i}><b>{a.type}</b>: {a.explanation} Expected: {a.expected_range}; actual: {a.actual_value}</p>)}</div><form className="card" onSubmit={ask}><h3>Safe HR Assistant</h3><input value={question} onChange={e=>setQuestion(e.target.value)}/><button className="btn btn-primary">Ask</button>{answer&&<pre>{JSON.stringify(answer.result,null,2)}</pre>}</form><div className="card"><h3>Policy Assistant</h3><label>Upload .txt or .md policy<input type="file" accept=".txt,.md" onChange={upload}/></label><form onSubmit={askPolicy}><input placeholder="Ask a policy question" value={policyQuestion} onChange={e=>setPolicyQuestion(e.target.value)}/><button className="btn btn-primary">Ask Policy</button></form>{policyAnswer&&<><p>{policyAnswer.answer}</p><p><b>Sources:</b> {policyAnswer.sources.map(s=>`${s.document} - ${s.section}`).join(', ')||'None'}</p></>}</div></div>
}
